<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">

    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>
            
      
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php endif; ?>
    

            


            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>  
			<div class="row-product">
			<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
            
			<?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>
			<p class="charms"><a  href="http://mishky.com/buy/media/wysiwyg/_Charms_.jpg" class="seecharm"><?php echo $this->__('See Charms') ?> </a></p>
        </div> 
		
		

<script type="text/javascript">// <![CDATA[
	jQuery.noConflict();

	jQuery(document).ready(function() {
	 jQuery(".seecharm").fancybox({ 'hideOnContentClick': false,'zoomSpeedIn': 300, 'zoomSpeedOut': 300, 'overlayShow': false });
		});

	// ]]></script>


		<?php //print_r($_product) ?>
                <div class="share bordercolor"><!-- AddThis Button BEGIN -->
		<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_10"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-51f795ec5b9a0e6a"></script>
<!-- AddThis Button END -->
		</div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="clearer"></div>
        
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
    	productAddToCartForm.submit = function(button, url) {
		if (this.validator.validate()) {
			var form = this.form;
			var oldUrl = form.action;
			if (url) {
				form.action = url;
			}
			var e = null;
			// Start of our new ajax code
			if (!url) {
				url = jQuery('#product_addtocart_form').attr('action');
			}
			url = url.replace("checkout/cart","ajax/index"); // New Code
			var data = jQuery('#product_addtocart_form').serialize();
			data += '&isAjax=1';
			jQuery('#ajax_loader').show();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					type : 'post',
					data : data,
					success : function(data) {
						jQuery('#ajax_loader').hide();
						if(data.status == 'ERROR'){
											jQuery('body').append('<div class="alert"></div>');
						jQuery('.alert').slideDown(400);
								jQuery('.alert').html(data.message).append('<button></button>');
				jQuery('button').click(function () {
                jQuery('.alert').slideUp(400);
                 });	
					jQuery('.alert').slideDown('400',function(){
									 	setTimeout(function(){
											jQuery('.alert').slideUp('400',function(){jQuery(this).slideUp(400)});
										},7000)
									 });
									 			jQuery('.block-cart-header .cart-content').hide();
			jQuery('.block-cart-header  .amount a').hover(function(){
				jQuery('.block-cart-header .cart-content').stop(true, true).slideDown(400);
			},function(){
				jQuery('.block-cart-header .cart-content').stop(true, true).delay(400).slideUp(300);
			}); 
						}else{
													jQuery('body').append('<div class="alert"></div>');
						jQuery('.alert').slideDown(400);
									jQuery('.alert').html(data.message).append('<button></button>');
									jQuery('.alert').html(data.message).wrapInner('<a class="alert-link" href="<?php echo $this->getUrl('checkout/cart') ?>"></a>');
				jQuery('button').click(function () {
                jQuery('.alert').slideUp(400);
                 });	
					jQuery('.alert').slideDown('400',function(){
									 	setTimeout(function(){
											jQuery('.alert').slideUp('400',function(){jQuery(this).slideUp(400)});
										},7000)
									 });
									 			jQuery('.block-cart-header .cart-content').hide();
			jQuery('.block-cart-header  .amount a').hover(function(){
				jQuery('.block-cart-header .cart-content').stop(true, true).slideDown(400);
			},function(){
				jQuery('.block-cart-header .cart-content').stop(true, true).delay(400).slideUp(300);
			}); 
	                        if(jQuery('.block-cart')){
	                            jQuery('.block-cart').replaceWith(data.sidebar);
	                        }
	                        if(jQuery('.header .links')){
	                            jQuery('.header .links').replaceWith(data.toplink);
	                        }
										if(jQuery('.block-cart-header')){
	            jQuery('.block-cart-header').replaceWith(data.sidebar_header);
	        }
						}
					}
				});
			} catch (e) {
			}
			// End of our new ajax code
			this.form.action = oldUrl;
			if (e) {
				throw e;
			}
		}
	}.bind(productAddToCartForm);
    productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

    <div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
       
        <?php echo $this->getChildHtml('product_additional_data') ?>
        
        <?php $attStuff= $_product->getData(); ?>
  		<?php if( !empty( $attStuff['videoid'] ) ): ?>        
		<div class="video">
			 <p><span>Video review of:</span> Lorem ipsum dolor sit amet conse ctetur adipisicing elit</p>
			 <iframe src="<?php echo $attStuff['videoid']; ?>" frameborder="0" allowfullscreen></iframe>
		</div>
		<?php endif; ?>
         
    </div>
</div><?php echo $this->getChildHtml('upsell_products') ?>
